name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - .github/workflows/main.yml
      - Cargo.toml

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install cargo-lambda
        run: pip install -r requirements.txt

      - name: Lint
        run: cargo clippy

      - name: Test
        run: cargo test

      - name: Build
        run: cargo lambda build --release --output-format zip

      - name: Deploy to AWS
        run: aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file=fileb://target/lambda/$LAMBDA_FUNCTION_NAME/bootstrap.zip
