name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/main.yml'
      - 'Cargo.toml'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install cargo-lambda
        run: pip install -r requirements.txt

      - name: Test
        run: cargo test

      - name: Build
        run: cargo lambda build --release --output-format zip

      - name: Deploy to AWS
        run: aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file=fileb://target/lambda/$LAMBDA_FUNCTION_NAME/bootstrap.zip
