name: Update Lambda Runtime

on:
  workflow_dispatch:
    inputs:
      runtime:
        type: choice
        description: 'Choose a Lambda Runtime'
        required: true
        options:
        - nodejs18.x
        - provided.al2

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}
      LAMBDA_RUNTIME: ${{ github.event.inputs.runtime }}
      LAMBDA_HANDLER: ${{ github.event.inputs.runtime == 'provided.al2' && 'bootstrap' || 'index.handler' }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update AWS Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name $LAMBDA_FUNCTION_NAME \
            --runtime $LAMBDA_RUNTIME \
            --handler $LAMBDA_HANDLER
