name: Update Lambda Runtime

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: lambda-proxy

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update AWS Lambda Runtime
        run: aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --runtime nodejs18.x
