name: Update Lambda Runtime

on:
  workflow_dispatch:
    inputs:
      runtime:
        type: choice
        description: 'Choose a Lambda Runtime'
        required: true
        options:
        - nodejs18.x
        - provided.al2

permissions:
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}
      LAMBDA_RUNTIME: ${{ github.event.inputs.runtime }}
      LAMBDA_HANDLER: ${{ github.event.inputs.runtime == 'provided.al2' && 'bootstrap' || 'index.handler' }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update AWS Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name $LAMBDA_FUNCTION_NAME \
            --runtime $LAMBDA_RUNTIME \
            --handler $LAMBDA_HANDLER
